### ISSUE TITLE
Latest of RDP Client Error

### ISSUE THREAD

**Issue by tayvermtos** [tksh164/rdclauncher#72]
Hi 

The latest version of the RDP client when trying to connect via a DNS name or IP address it come up with the following error:

![image](https://github.com/tksh164/rdclauncher/assets/132401624/71c41766-bc7f-4ff5-a635-5e8503c06227)

Is there anything that can be done about it, or am I missing something? 

I have used it in the past without any issues.

Many thanks for Your gr8 tool!!

**Comment by tksh164** [comment]
@tayvermtos - Thank you for catching this. The RDC Launcher generates a temporary .rdp file for establish a connection. But it is not normal .rdp file from the MSRDC side view. I think that the latest MSRDC began to verify the .rdp file integrity.

I am currently working on a new remote desktop client app that does not depend on MSRDC. The first version will be released in early August.

Thanks

**Comment by tayvermtos** [comment]
Hi

Thanks so much for this info! I'll have a go at it later on today.

Many thanks
